#!/usr/bin/env python3
"""Generate nginx site config from packageconfig gateway profile."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from load_config import get_profile, load_packageconfig  # noqa: E402


def render_site(site: dict) -> str:
    host = site["host"]
    aliases = site.get("aliases") or []
    server_names = " ".join([host, *aliases])
    backend = site["backend"]
    backend_port = site.get("backendPort", 8080)
    ui = site["ui"]
    ui_port = site.get("uiPort", 80)
    health = site.get("healthPath", "/api/health")
    create = site.get("createPath", "/api/invoices")

    return f"""# --- {host} ---
server {{
  listen 443 ssl;
  http2 on;
  server_name {server_names};

  ssl_certificate     /etc/nginx/certs/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/privkey.pem;
  ssl_protocols       TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;

  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  add_header X-Content-Type-Options nosniff always;
  add_header X-Frame-Options DENY always;
  add_header Referrer-Policy strict-origin-when-cross-origin always;

  limit_conn addr 40;

  set ${backend.replace("-", "_")}_upstream {backend}:{backend_port};
  set ${ui.replace("-", "_")}_upstream {ui}:{ui_port};

  location = {health} {{
    proxy_pass http://${backend.replace("-", "_")}_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }}

  location = {create} {{
    limit_req zone=api_create burst=2 nodelay;
    proxy_pass http://${backend.replace("-", "_")}_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }}

  location /api/ {{
    limit_req zone=api_public burst=40 nodelay;
    proxy_pass http://${backend.replace("-", "_")}_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }}

  location / {{
    proxy_pass http://${ui.replace("-", "_")}_upstream;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }}
}}
"""


def render_gateway(conf: dict, profile: str, prof: dict, output_name: str = "domains.conf") -> str:
    sites = prof.get("sites") or []
    parts = [
        "# Generated by infra/lib/generate.py — edit packageconfig sites[] and re-install",
        "resolver 127.0.0.11 valid=10s ipv6=off;",
        "",
        "server {",
        "  listen 80 default_server;",
        "  server_name _;",
        "  location /.well-known/acme-challenge/ { root /var/www/certbot; }",
        "  location / { return 301 https://$host$request_uri; }",
        "}",
        "",
    ]
    for site in sites:
        parts.append(render_site(site))
        parts.append("")
    include = prof.get("templates", {}).get("nginxInclude")
    if include and Path(include).name != output_name:
        parts.append(f"include /etc/nginx/conf.d/{Path(include).name};")
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("packageconfig")
    ap.add_argument("--profile", default="gateway")
    ap.add_argument("-o", "--output", required=True)
    args = ap.parse_args()
    conf = load_packageconfig(Path(args.packageconfig))
    prof = get_profile(conf, args.profile)
    out = render_gateway(conf, args.profile, prof, Path(args.output).name)
    Path(args.output).write_text(out, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
