#!/usr/bin/env python3
"""Generate nginx site config from packageconfig gateway profile."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from load_config import get_profile, load_packageconfig  # noqa: E402


def render_site(site: dict) -> str:
    host = site["host"]
    aliases = site.get("aliases") or []
    server_names = " ".join([host, *aliases])
    backend = site["backend"]
    backend_port = site.get("backendPort", 8080)
    ui = site["ui"]
    ui_port = site.get("uiPort", 80)
    health = site.get("healthPath", "/api/health")
    create = site.get("createPath") or ""
    be_var = backend.replace("-", "_")
    ui_var = ui.replace("-", "_")
    cert = site.get("sslCertificate") or "/etc/nginx/certs/fullchain.pem"
    key = site.get("sslCertificateKey") or "/etc/nginx/certs/privkey.pem"
    proxy_headers = f"""    proxy_pass http://${be_var}_upstream;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;"""
    create_block = ""
    if create:
        create_block = f"""
  location = {create} {{
    limit_req zone=api_create burst=2 nodelay;
{proxy_headers}
  }}
"""

    return f"""# --- {host} ---
server {{
  listen 443 ssl;
  http2 on;
  server_name {server_names};

  ssl_certificate     {cert};
  ssl_certificate_key {key};
  ssl_protocols       TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;

  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  add_header X-Content-Type-Options nosniff always;
  add_header X-Frame-Options DENY always;
  add_header Referrer-Policy strict-origin-when-cross-origin always;

  limit_conn addr 40;

  set ${be_var}_upstream {backend}:{backend_port};
  set ${ui_var}_upstream {ui}:{ui_port};

  location /_vibed/hooks/ {{
    proxy_pass http://host.docker.internal:19200;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }}

  location = {health} {{
{proxy_headers}
  }}
{create_block}
  location /api/ {{
    limit_req zone=api_public burst=40 nodelay;
{proxy_headers}
  }}

  location / {{
    proxy_pass http://${ui_var}_upstream;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }}
}}
"""


def render_app_sites(prof: dict) -> str:
    """Per-app sites.conf (no ACME block — host 00-default.conf owns that)."""
    sites = prof.get("sites") or []
    parts = [
        "# Generated by lib/generate.py — app sites for host gateway apps/{name}/sites.conf",
        "",
    ]
    for site in sites:
        parts.append(render_site(site))
        parts.append("")
    return "\n".join(parts)


def render_gateway(conf: dict, profile: str, prof: dict, output_name: str = "domains.conf") -> str:
    """Full standalone conf (legacy) or app-only when output is sites.conf."""
    if Path(output_name).name == "sites.conf":
        return render_app_sites(prof)
    sites = prof.get("sites") or []
    parts = [
        "# Generated by lib/generate.py — edit packageconfig sites[] and re-install",
        "resolver 127.0.0.11 valid=10s ipv6=off;",
        "",
        "server {",
        "  listen 80 default_server;",
        "  server_name _;",
        "  location /.well-known/acme-challenge/ { root /var/www/certbot; }",
        "  location / { return 301 https://$host$request_uri; }",
        "}",
        "",
    ]
    for site in sites:
        parts.append(render_site(site))
        parts.append("")
    include = prof.get("templates", {}).get("nginxInclude")
    if include and Path(include).name != output_name:
        parts.append(f"include /etc/nginx/conf.d/{Path(include).name};")
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("packageconfig")
    ap.add_argument("--profile", default="gateway")
    ap.add_argument("-o", "--output", required=True)
    ap.add_argument(
        "--mode",
        choices=("full", "app"),
        default=None,
        help="full=standalone domains.conf; app=sites.conf for host gateway",
    )
    args = ap.parse_args()
    conf = load_packageconfig(Path(args.packageconfig))
    prof = get_profile(conf, args.profile)
    out_name = Path(args.output).name
    mode = args.mode
    if mode is None:
        mode = "app" if out_name == "sites.conf" else "full"
    if mode == "app":
        out = render_app_sites(prof)
    else:
        out = render_gateway(conf, args.profile, prof, out_name)
    Path(args.output).write_text(out, encoding="utf-8")
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
