#!/usr/bin/env python3
"""Build product dist/ from templates/*.yaml — operators wget install-*.sh from dist."""
from __future__ import annotations

import argparse
import shutil
import stat
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from product_config import (  # noqa: E402
    compile_packageconfig,
    dump_yaml,
    load_product,
    write_app_config,
)


def _chmod_x(path: Path) -> None:
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _write(path: Path, text: str, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    if executable:
        _chmod_x(path)


def _copy_generic(packager: Path, out: Path, name: str) -> None:
    src = packager / "templates" / "generic" / name
    if not src.is_file():
        raise FileNotFoundError(f"missing generic template {src}")
    shutil.copy2(src, out / name)
    _chmod_x(out / name)


def _env_api(meta: dict, conf: dict, api: dict) -> str:
    au = conf["profiles"]["api"]["autoUpdate"]
    return f"""# Generated by vibed-infra package — edit .env on the VPS, not in git dist.
API_TOKEN=change-me-api-token
DOCKER_NETWORK={meta['network']}
DOCKER_NAME={meta['apiContainer']}
BACKEND_IMAGE={conf['images']['backend']}
HOST_PORT={meta['apiPort']}
DATA_DIR=./data
CONFIG_FILE=api-app.yaml
API_MEMORY_LIMIT=256m
{au['flag']}=0
{au['intervalEnv']}=30
{au['stopTimeoutEnv']}=60
"""


def _env_ui(meta: dict, conf: dict, ui: dict) -> str:
    au = conf["profiles"]["ui"]["autoUpdate"]
    return f"""# Generated by vibed-infra package
DOCKER_NETWORK={meta['network']}
UI_NAME={meta['uiContainer']}
UI_IMAGE={conf['images']['ui']}
UI_MEMORY_LIMIT=32m
{au['flag']}=0
{au['intervalEnv']}=20
{au['stopTimeoutEnv']}=30
"""


def _env_nodes(meta: dict, conf: dict, nodes: dict) -> str:
    au = conf["profiles"]["nodes"]["autoUpdate"]
    api_host = meta["apiContainer"]
    return f"""# Generated by vibed-infra package
API_URL=http://{api_host}:{meta['apiPort']}
API_TOKEN=change-me-api-token
DOCKER_NETWORK={meta['network']}
WORKER_IMAGE={conf['images']['worker']}
WORKER_CONTAINER_NAME={meta['workerContainer']}
WORKER_ROLE=heartbeat
INTERVAL_SEC=60
WORKER_MEMORY_LIMIT=64m
{au['flag']}=0
{au['intervalEnv']}=30
{au['stopTimeoutEnv']}=30
"""


def _env_gateway(meta: dict, conf: dict, sites: list) -> str:
    au = conf["profiles"]["gateway"]["autoUpdate"]
    host = sites[0]["host"] if sites else "example.com"
    cert_dir = sites[0].get("tlsCertDir", f"/etc/letsencrypt/live/{host}") if sites else "/etc/letsencrypt/live/example.com"
    flags = au.get("flags") or ["GATEWAY_AUTO_UPDATE"]
    flag_lines = "\n".join(f"{f}=0" for f in flags)
    return f"""# Generated by vibed-infra package
DOCKER_NETWORK={meta['network']}
GATEWAY_NAME={meta['gatewayContainer']}
NGINX_IMAGE={conf['images']['nginx']}
TLS_FULLCHAIN={cert_dir}/fullchain.pem
TLS_PRIVKEY={cert_dir}/privkey.pem
CERTBOT_WWW=./certbot-www
HTTP_PORT=80
HTTPS_PORT=443
GATEWAY_MEMORY_LIMIT=64m
{flag_lines}
{au.get('intervalEnv', 'GATEWAY_AUTO_UPDATE_INTERVAL_MIN')}=20
{au.get('stopTimeoutEnv', 'GATEWAY_STOP_TIMEOUT')}=30
"""


def _compose_workers(meta: dict, conf: dict) -> str:
    return f"""# Generated by vibed-infra package
networks:
  edge:
    external: true
    name: ${{DOCKER_NETWORK:-{meta['network']}}}

services:
  worker:
    image: ${{WORKER_IMAGE:-{conf['images']['worker']}}}
    container_name: ${{WORKER_CONTAINER_NAME:-{meta['workerContainer']}}}
    restart: unless-stopped
    mem_limit: ${{WORKER_MEMORY_LIMIT:-64m}}
    env_file: .env
    environment:
      WORKER_ROLE: ${{WORKER_ROLE:-heartbeat}}
      WORKER_CONFIG: /config/workers.yaml
      API_URL: ${{API_URL:-http://{meta['apiContainer']}:{meta['apiPort']}}}
      INTERVAL_SEC: ${{INTERVAL_SEC:-60}}
    volumes:
      - ./logs:/data/logs
      - ./nodes-workers.yaml:/config/workers.yaml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - edge
"""


def _install_wrapper(profile: str, packager_raw: str) -> str:
    return f"""#!/usr/bin/env bash
# wget install — profile {profile}. Generated by vibed-infra package.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]:-$0}}")" && pwd)"
PACKAGER_RAW="${{PACKAGER_RAW:-{packager_raw}}}"
export PACKAGECONFIG_URL="${{PACKAGECONFIG_URL:-$SCRIPT_DIR/packageconfig.yaml}}"
export PRODUCT_RAW="${{PRODUCT_RAW:-$SCRIPT_DIR}}"
export INFRA_PROFILE={profile}
export INSTALL_DIR="${{INSTALL_DIR:-.}}"
if [[ "$PACKAGER_RAW" =~ ^/ ]]; then
  exec bash "$PACKAGER_RAW/install.sh" --profile {profile}
fi
if command -v curl >/dev/null 2>&1; then
  exec bash <(curl -fsSL "${{PACKAGER_RAW}}/install.sh") --profile {profile}
else
  exec bash <(wget -qO- "${{PACKAGER_RAW}}/install.sh") --profile {profile}
fi
"""


def build_dist(product_dir: Path, out_dir: Path, packager_root: Path) -> None:
    product_dir = product_dir.resolve()
    out_dir = out_dir.resolve()
    packager_root = packager_root.resolve()

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    product = load_product(product_dir)
    tpl = product["templates_dir"]
    raw_base = str(out_dir)  # local dist path; operators override PRODUCT_RAW via wget URL

    conf = compile_packageconfig(
        product,
        raw_base=raw_base,
        packager_raw=str(packager_root),
    )
    meta = conf["_meta"]
    comps = product["components"]
    sites = conf["profiles"]["gateway"].get("sites") or []

    # Copy source configs into dist
    shutil.copy2(tpl / "vibed-infra-config.yml", out_dir / "vibed-infra-config.yml")
    refs = product["infra"].get("templates") or {}
    for dst, key in (
        ("api-config.yaml", "api"),
        ("ui-config.yaml", "ui"),
        ("nodes-config.yaml", "nodes"),
    ):
        src_name = refs.get(key) or f"{key}-config.yaml"
        shutil.copy2(tpl / src_name, out_dir / dst)

    _write(out_dir / "packageconfig.yaml", dump_yaml(conf))

    write_app_config(comps["api"], out_dir / "api-app.yaml")
    write_app_config(comps["nodes"], out_dir / "nodes-workers.yaml")

    _write(out_dir / ".env.api.example", _env_api(meta, conf, comps["api"]))
    _write(out_dir / ".env.ui.example", _env_ui(meta, conf, comps["ui"]))
    _write(out_dir / ".env.nodes.example", _env_nodes(meta, conf, comps["nodes"]))
    _write(out_dir / ".env.gateway.example", _env_gateway(meta, conf, sites))
    _write(out_dir / "docker-compose.workers.yml", _compose_workers(meta, conf))

    gw_dir = out_dir / "gateway"
    gw_dir.mkdir()
    shutil.copy2(packager_root / "templates" / "generic" / "gateway" / "nginx.conf", gw_dir / "nginx.conf")

    for script in (
        "start-api.sh",
        "start-ui.sh",
        "start-nodes.sh",
        "start-gateway.sh",
        "update-api.sh",
        "update-ui.sh",
        "update-nodes.sh",
        "update-gateway.sh",
        "gen-dev-certs.sh",
    ):
        _copy_generic(packager_root, out_dir, script)

    packager_raw_url = "https://raw.githubusercontent.com/naiemk/vibed-infra/main"
    for profile in ("api", "ui", "nodes", "gateway"):
        name = f"install-{profile}.sh"
        _write(out_dir / name, _install_wrapper(profile, packager_raw_url), executable=True)

    readme = f"""# dist — generated by vibed-infra package

Do not edit by hand. Run `../package.sh` from the product root and commit.

## VPS install

```bash
wget -qO- https://raw.githubusercontent.com/ORG/REPO/main/dist/install-api.sh | bash
wget -qO- https://raw.githubusercontent.com/ORG/REPO/main/dist/install-ui.sh | bash
wget -qO- https://raw.githubusercontent.com/ORG/REPO/main/dist/install-nodes.sh | bash
wget -qO- https://raw.githubusercontent.com/ORG/REPO/main/dist/install-gateway.sh | bash
```

Network: `{meta['network']}`. API container: `{meta['apiContainer']}`.
"""
    _write(out_dir / "README.md", readme)
    print(f"packaged: {out_dir}")


def main() -> int:
    ap = argparse.ArgumentParser(description="Build product dist/ for VPS wget install")
    ap.add_argument("--product", required=True, help="Product root (contains templates/)")
    ap.add_argument("--out", required=True, help="Output dist directory")
    ap.add_argument(
        "--packager",
        default=str(Path(__file__).resolve().parent.parent),
        help="vibed-infra root",
    )
    args = ap.parse_args()
    build_dist(Path(args.product), Path(args.out), Path(args.packager))
    return 0


if __name__ == "__main__":
    sys.exit(main())
