#!/usr/bin/env python3
"""Build product dist/ from templates/*.yaml — operators wget install-*.sh from dist."""
from __future__ import annotations

import argparse
import shutil
import stat
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from product_config import (  # noqa: E402
    compile_packageconfig,
    dump_yaml,
    load_product,
    write_app_config,
)


def _chmod_x(path: Path) -> None:
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def _write(path: Path, text: str, executable: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    if executable:
        _chmod_x(path)


def _copy_generic(packager: Path, out: Path, name: str) -> None:
    src = packager / "templates" / "generic" / name
    if not src.is_file():
        raise FileNotFoundError(f"missing generic template {src}")
    shutil.copy2(src, out / name)
    _chmod_x(out / name)


# Also fix _env_api - remove unused name variable at start of _env_api
def _env_api(meta: dict, conf: dict, api: dict) -> str:
    au = conf["profiles"]["api"]["autoUpdate"]
    return f"""# Generated by vibed-infra package — edit .env on the VPS, not in git dist.
API_TOKEN=change-me-api-token
DOCKER_NETWORK={meta['network']}
DOCKER_NAME={meta['apiContainer']}
BACKEND_IMAGE={conf['images']['backend']}
HOST_PORT={meta['apiPort']}
# Durable data uses Docker named volume ${{DOCKER_NAME}}-data by default.
# DATA_VOLUME=custom-data-vol
# DATA_BIND=1
# DATA_DIR=./data
CONFIG_FILE=api-app.yaml
API_MEMORY_LIMIT=256m
# Persist logs: named volume ${{DOCKER_NAME}}-persist + ship sidecar (default on).
# PERSIST_LOG_VOLUME=custom-persist-vol
# PERSIST_LOGS=0
# PERSIST_LOG_BIND=1
# PERSIST_LOG_DIR=./persist-logs
{au['flag']}=0
{au['intervalEnv']}=30
{au['stopTimeoutEnv']}=60
DOCKER_AUTO_PRUNE=1
DOCKER_PRUNE_UNUSED=0
DOCKER_PRUNE_UNTIL=72h
"""


def _env_ui(meta: dict, conf: dict, ui: dict) -> str:
    au = conf["profiles"]["ui"]["autoUpdate"]
    return f"""# Generated by vibed-infra package
DOCKER_NETWORK={meta['network']}
UI_NAME={meta['uiContainer']}
UI_IMAGE={conf['images']['ui']}
UI_MEMORY_LIMIT=32m
{au['flag']}=0
{au['intervalEnv']}=20
{au['stopTimeoutEnv']}=30
DOCKER_AUTO_PRUNE=1
DOCKER_PRUNE_UNUSED=0
DOCKER_PRUNE_UNTIL=72h
"""


def _env_nodes(meta: dict, conf: dict, nodes: dict) -> str:
    au = conf["profiles"]["nodes"]["autoUpdate"]
    api_host = meta["apiContainer"]
    return f"""# Generated by vibed-infra package
API_URL=http://{api_host}:{meta['apiPort']}
API_TOKEN=change-me-api-token
DOCKER_NETWORK={meta['network']}
WORKER_IMAGE={conf['images']['worker']}
WORKER_CONTAINER_NAME={meta['workerContainer']}
WORKER_ROLE=heartbeat
INTERVAL_SEC=60
WORKER_MEMORY_LIMIT=64m
# Logs + persist use named volumes by default (${{WORKER_CONTAINER_NAME}}-logs / -persist).
# WORKER_LOG_VOLUME=
# PERSIST_LOG_VOLUME=
# PERSIST_LOGS=0
# LOGS_BIND=1
# LOGS_DIR=./logs
{au['flag']}=0
{au['intervalEnv']}=30
{au['stopTimeoutEnv']}=30
DOCKER_AUTO_PRUNE=1
DOCKER_PRUNE_UNUSED=0
DOCKER_PRUNE_UNTIL=72h
"""


def _env_gateway(meta: dict, conf: dict, sites: list) -> str:
    au = conf["profiles"]["gateway"]["autoUpdate"]
    gw = conf["profiles"]["gateway"]
    # Host gateway stores PEMs under ./certs (setup-tls.sh). tlsCertDir is legacy/docs only
    # unless it already points at a relative ./certs tree.
    cert_dir = "./certs"
    if sites:
        raw = sites[0].get("tlsCertDir") or ""
        if raw.startswith("./certs") or raw.rstrip("/") == "certs":
            cert_dir = raw.rstrip("/")
    flags = au.get("flags") or ["GATEWAY_AUTO_UPDATE"]
    flag_lines = "\n".join(f"{f}=0" for f in flags)
    public_ip = gw.get("publicIp") or meta.get("publicIp") or ""
    tls_email = gw.get("tlsEmail") or meta.get("tlsEmail") or ""
    return f"""# Generated by vibed-infra package — thin product wrapper; host lives in GATEWAY_HOME
DOCKER_NETWORK={meta['network']}
GATEWAY_NAME={meta['gatewayContainer']}
GATEWAY_HOME=~/services/gateway
NGINX_IMAGE={conf['images']['nginx']}
TLS_FULLCHAIN={cert_dir}/fullchain.pem
TLS_PRIVKEY={cert_dir}/privkey.pem
TLS_MODE=
TLS_EMAIL={tls_email}
GATEWAY_PUBLIC_IP={public_ip}
CERTBOT_WWW=./certbot-www
HTTP_PORT=80
HTTPS_PORT=443
GATEWAY_MEMORY_LIMIT=64m
{flag_lines}
{au.get('intervalEnv', 'GATEWAY_AUTO_UPDATE_INTERVAL_MIN')}=20
{au.get('stopTimeoutEnv', 'GATEWAY_STOP_TIMEOUT')}=30
DOCKER_AUTO_PRUNE=1
DOCKER_PRUNE_UNUSED=0
DOCKER_PRUNE_UNTIL=72h
"""


def _dns_skill(product_name: str, sites: list, public_ip: str = "") -> str:
    tmpl = (
        Path(__file__).resolve().parent.parent
        / "templates"
        / "generic"
        / "DNS-SKILL.md.tmpl"
    )
    text = tmpl.read_text(encoding="utf-8")
    ip = (public_ip or "").strip()
    value = ip if ip else "{{VPS_IP}}"
    lines: list[str] = []
    for site in sites:
        host = site["host"]
        lines.append(f"| `{host}` | A | `{value}` |")
        for alias in site.get("aliases") or []:
            lines.append(f"| `{alias}` | A | `{value}` |")
    table = "| Hostname | Type | Value |\n|----------|------|-------|\n" + "\n".join(lines)
    if not lines:
        table = "_No gateway.sites[] configured — add hosts in vibed-infra-config.yml and re-package._"
    if ip:
        ip_instruction = (
            f"Confirm IPv4 `{ip}` with the operator before changing records — do not invent a different IP."
        )
        before_steps = f"""1. **Confirm the VPS public IPv4 is `{ip}`** (from `gateway.publicIp` in product config). If the operator says the IP changed, use their new IP and ask them to update config / re-package.
2. Optionally ask for IPv6 if they want AAAA records.
3. Confirm which DNS provider UI they use (Cloudflare, registrar, Route53, etc.).
4. Ensure you are logged into that provider in the browser before editing records."""
        ip_safety = f"\n- The packaged IP is `{ip}`; only change it if the operator confirms a new address."
    else:
        ip_instruction = "Ask the user for the VPS IPv4 address first — never invent an IP."
        before_steps = """1. **Ask the user for the VPS public IPv4 address.** Do not guess or invent IPs.
2. Optionally ask for IPv6 if they want AAAA records.
3. Confirm which DNS provider UI they use (Cloudflare, registrar, Route53, etc.).
4. Ensure you are logged into that provider in the browser before editing records.

Placeholder used below: `{{VPS_IP}}` — replace with the IPv4 the user gives you."""
        ip_safety = ""
    return (
        text.replace("{{PRODUCT_NAME}}", product_name)
        .replace("{{DNS_RECORDS}}", table)
        .replace("{{IP_INSTRUCTION}}", ip_instruction)
        .replace("{{BEFORE_STEPS}}", before_steps)
        .replace("{{IP_SAFETY}}", ip_safety)
    )

def _compose_workers(meta: dict, conf: dict) -> str:
    return f"""# Generated by vibed-infra package
networks:
  edge:
    external: true
    name: ${{DOCKER_NETWORK:-{meta['network']}}}

volumes:
  worker_logs:
    external: true
    name: ${{WORKER_LOG_VOLUME:-{meta['workerContainer']}-logs}}
  worker_persist:
    external: true
    name: ${{PERSIST_LOG_VOLUME:-{meta['workerContainer']}-persist}}

services:
  worker:
    image: ${{WORKER_IMAGE:-{conf['images']['worker']}}}
    container_name: ${{WORKER_CONTAINER_NAME:-{meta['workerContainer']}}}
    restart: unless-stopped
    mem_limit: ${{WORKER_MEMORY_LIMIT:-64m}}
    env_file: .env
    labels:
      vibed.managed: "1"
      vibed.role: nodes
      vibed.logs-volume: ${{WORKER_LOG_VOLUME:-{meta['workerContainer']}-logs}}
      vibed.persist-volume: ${{PERSIST_LOG_VOLUME:-{meta['workerContainer']}-persist}}
    environment:
      WORKER_ROLE: ${{WORKER_ROLE:-heartbeat}}
      WORKER_CONFIG: /config/workers.yaml
      API_URL: ${{API_URL:-http://{meta['apiContainer']}:{meta['apiPort']}}}
      INTERVAL_SEC: ${{INTERVAL_SEC:-60}}
      PERSIST_LOG_DIR: /persist-logs
    volumes:
      - worker_logs:/data/logs
      - worker_persist:/persist-logs
      - ./nodes-workers.yaml:/config/workers.yaml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - edge
"""


def _install_wrapper(profile: str, packager_raw: str, product_raw: str | None = None) -> str:
    if product_raw:
        product_default = product_raw.rstrip("/")
        pc_default = f"{product_default}/packageconfig.yaml"
    else:
        product_default = "$SCRIPT_DIR"
        pc_default = "$SCRIPT_DIR/packageconfig.yaml"
    return f"""#!/usr/bin/env bash
# wget install — profile {profile}. Generated by vibed-infra package.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]:-$0}}")" && pwd)"
PACKAGER_RAW="${{PACKAGER_RAW:-{packager_raw}}}"
export PACKAGER_RAW
export PRODUCT_RAW="${{PRODUCT_RAW:-{product_default}}}"
export PACKAGECONFIG_URL="${{PACKAGECONFIG_URL:-{pc_default}}}"
export INFRA_PROFILE={profile}
export INSTALL_DIR="${{INSTALL_DIR:-.}}"
if [[ "$PACKAGER_RAW" =~ ^/ ]]; then
  exec bash "$PACKAGER_RAW/install.sh" --profile {profile}
fi
if command -v curl >/dev/null 2>&1; then
  exec bash <(curl -fsSL "${{PACKAGER_RAW}}/install.sh") --profile {profile}
else
  exec bash <(wget -qO- "${{PACKAGER_RAW}}/install.sh") --profile {profile}
fi
"""


def build_dist(
    product_dir: Path,
    out_dir: Path,
    packager_root: Path,
    *,
    raw_base: str | None = None,
    packager_raw: str | None = None,
) -> None:
    product_dir = product_dir.resolve()
    out_dir = out_dir.resolve()
    packager_root = packager_root.resolve()

    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True)

    product = load_product(product_dir)
    tpl = product["templates_dir"]
    # Default local paths; pass http(s) raw_base/packager_raw for wget|bash installs.
    raw_base_val = (raw_base if raw_base is not None else str(out_dir)).rstrip("/")
    packager_raw_val = (
        packager_raw if packager_raw is not None else str(packager_root)
    ).rstrip("/")

    conf = compile_packageconfig(
        product,
        raw_base=raw_base_val,
        packager_raw=packager_raw_val,
    )
    meta = conf["_meta"]
    comps = product["components"]
    sites = conf["profiles"]["gateway"].get("sites") or []

    # Copy source configs into dist
    shutil.copy2(tpl / "vibed-infra-config.yml", out_dir / "vibed-infra-config.yml")
    refs = product["infra"].get("templates") or {}
    for dst, key in (
        ("api-config.yaml", "api"),
        ("ui-config.yaml", "ui"),
        ("nodes-config.yaml", "nodes"),
    ):
        src_name = refs.get(key) or f"{key}-config.yaml"
        shutil.copy2(tpl / src_name, out_dir / dst)

    _write(out_dir / "packageconfig.yaml", dump_yaml(conf))

    write_app_config(comps["api"], out_dir / "api-app.yaml")
    write_app_config(comps["nodes"], out_dir / "nodes-workers.yaml")

    _write(out_dir / ".env.api.example", _env_api(meta, conf, comps["api"]))
    _write(out_dir / ".env.ui.example", _env_ui(meta, conf, comps["ui"]))
    _write(out_dir / ".env.nodes.example", _env_nodes(meta, conf, comps["nodes"]))
    _write(out_dir / ".env.gateway.example", _env_gateway(meta, conf, sites))
    _write(out_dir / "docker-compose.workers.yml", _compose_workers(meta, conf))

    gw_dir = out_dir / "gateway"
    gw_dir.mkdir()
    shutil.copy2(packager_root / "templates" / "generic" / "gateway" / "nginx.conf", gw_dir / "nginx.conf")

    for script in (
        "start-api.sh",
        "start-ui.sh",
        "start-nodes.sh",
        "start-gateway.sh",
        "update-api.sh",
        "update-ui.sh",
        "update-nodes.sh",
        "update-gateway.sh",
        "gen-dev-certs.sh",
    ):
        _copy_generic(packager_root, out_dir, script)

    sidecar = packager_root / "templates" / "persist-logs" / "start-persist-sidecar.sh"
    if sidecar.is_file():
        shutil.copy2(sidecar, out_dir / "start-persist-sidecar.sh")
        _chmod_x(out_dir / "start-persist-sidecar.sh")

    # Bake HTTP URLs into install wrappers when packaging for wget serve; else GitHub default.
    if packager_raw_val.startswith("http://") or packager_raw_val.startswith("https://"):
        wrapper_packager = packager_raw_val
    else:
        wrapper_packager = "https://raw.githubusercontent.com/naiemk/vibed-infra/main"
    wrapper_product = (
        raw_base_val
        if raw_base_val.startswith("http://") or raw_base_val.startswith("https://")
        else None
    )
    notify_src = packager_root / "github" / "notify-vps-pull.py"
    if notify_src.is_file():
        shutil.copy2(notify_src, out_dir / "notify-vps-pull.py")
        _chmod_x(out_dir / "notify-vps-pull.py")

    for profile in ("api", "ui", "nodes", "gateway"):
        name = f"install-{profile}.sh"
        _write(
            out_dir / name,
            _install_wrapper(profile, wrapper_packager, wrapper_product),
            executable=True,
        )

    _write(
        out_dir / "DNS-SKILL.md",
        _dns_skill(
            meta.get("productName") or conf.get("name") or "app",
            sites,
            public_ip=str(meta.get("publicIp") or conf["profiles"]["gateway"].get("publicIp") or ""),
        ),
    )

    readme = f"""# dist — generated by vibed-infra package

Do not edit by hand. Run `../package.sh` from the product root and commit.

## VPS install

```bash
wget -qO- https://raw.githubusercontent.com/ORG/REPO/main/dist/install-api.sh | bash
wget -qO- https://raw.githubusercontent.com/ORG/REPO/main/dist/install-ui.sh | bash
wget -qO- https://raw.githubusercontent.com/ORG/REPO/main/dist/install-nodes.sh | bash
wget -qO- https://raw.githubusercontent.com/ORG/REPO/main/dist/install-gateway.sh | bash
```

Network: `{meta['network']}` (shared host edge). API container: `{meta['apiContainer']}`.
Gateway install bootstraps `~/services/gateway` once, then drops `apps/{{product}}/sites.conf`.

## Image updates

wget install registers this product with the machine update-agent. A GHCR `:main` push (reusable workflow + `id-token: write`) POSTs `/_vibed/hooks/ghcr` so the VPS pulls immediately. Cron `*_AUTO_UPDATE` is a backup. See the packager’s infra-update-agent skill.

## DNS (AU agent)

Copy [`DNS-SKILL.md`](DNS-SKILL.md) into an AU agent browser extension. Domains and `gateway.publicIp` are baked in when configured; confirm the IP with the operator.
"""
    _write(out_dir / "README.md", readme)
    print(f"packaged: {out_dir}")


def main() -> int:
    ap = argparse.ArgumentParser(description="Build product dist/ for VPS wget install")
    ap.add_argument("--product", required=True, help="Product root (contains templates/)")
    ap.add_argument("--out", required=True, help="Output dist directory")
    ap.add_argument(
        "--packager",
        default=str(Path(__file__).resolve().parent.parent),
        help="vibed-infra root",
    )
    ap.add_argument(
        "--raw-base",
        default=None,
        help="packageconfig rawBase + PRODUCT_RAW default (path or http URL)",
    )
    ap.add_argument(
        "--packager-raw",
        default=None,
        help="packageconfig packagerRaw + PACKAGER_RAW default (path or http URL)",
    )
    args = ap.parse_args()
    build_dist(
        Path(args.product),
        Path(args.out),
        Path(args.packager),
        raw_base=args.raw_base,
        packager_raw=args.packager_raw,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
